import type { components } from './api'

export type Me = components['schemas']['MeResource']
export type Role = components['schemas']['RoleResource']
export type PermissionItem = components['schemas']['PermissionResource']
export type Permission = components['schemas']['Permission']
export type UserListItem = components['schemas']['UserResource']
export type ChangeHistoryEntry = components['schemas']['ChangeHistoryResource']

export type LaravelPaginator<T> = {
  data: Array<T>
  links: {
    first: string | null
    last: string | null
    prev: string | null
    next: string | null
  }
  meta: {
    current_page: number
    from: number | null
    last_page: number
    links: Array<{
      url: string | null
      label: string
      active: boolean
    }>
    path: string | null
    per_page: number
    to: number | null
    total: number
  }
}

export type Paginated<T> = LaravelPaginator<T>

export type {
  AlertsRules,
  BankDetails,
  BusinessRulesDocument,
  BusinessRulesVersion,
  CalendarSettings,
  CancellationBand,
  CommissionRules,
  ConfigChange,
  ConfigPublisher,
  ConfigValidation,
  ConfigVersion,
  ConfigVersionDetail,
  ConfigVersionSummary,
  ConfigWarning,
  ConsentVersions,
  CopySettings,
  DiscountsRules,
  DocumentsRules,
  EngineSettingsDocument,
  EngineSettingsValidation,
  EngineSettingsVersion,
  ExtrasCatalogue,
  ExtrasCatalogueItem,
  ExtrasDocument,
  ExtrasVersion,
  FeesSettings,
  GuestsSettings,
  HoldsRules,
  LegalEntity,
  LocaleSettings,
  ManifestsRules,
  NoRate,
  PaymentsRules,
  PngFees,
  PriceCheckQuote,
  PriceCheckRow,
  PriceCheckStay,
  Quote,
  QuoteLine,
  RateDayOfWeek,
  RateLengthOfStay,
  RateOccupancy,
  RatePlan,
  RateRules,
  RateSeason,
  RateSupplement,
  RateTerms,
  RateYear,
  RatesDocument,
  RatesVersion,
  RetentionRules,
  RoomNightlyRate,
  RuleGroup,
  RuleRegistryCounts,
  RuleRegistryRow,
  RuleStatus,
  RuleWhere,
  SlaRules,
  StayNightLine,
  StayQuote,
  StayTaxLine,
  TaxRule,
} from './config'

export type {
  AllowedTransition,
  Booking,
  BookingAuditRow,
  BookingFormOptions,
  BookingListItem,
  BookingOwner,
  BookingRequestSummary,
  BookingQuote,
  BookingQuoteRequest,
  BookingSegment,
  BookingStatus,
  BookingType,
  ChannelOfOrigin,
  Contact,
  ContactSearchResult,
  CreateReservationRequest,
  CreateReservationResponse,
  Group,
  GroupSummary,
  HoldListItem,
  HoldListRules,
  MainChannel,
  MovePreview,
  PreferredChannel,
  PriceLine,
  RequestQueueItem,
  RequestQueueRules,
  WaitlistEntry,
} from './bookings'

export type {
  BookingConsent,
  Consent,
  ConsentDocument,
  ConsentSource,
  ContactInRow,
  Country,
  Guest,
  GuestIssue,
  GuestIssueSeverity,
  GuestListSummary,
  GuestExperienceDeparture,
  DepartureGuestExperience,
  GuestPreferences,
  GuestPreferencesInput,
  GuestResponse,
  GuestResponseInput,
  MaskedNote,
  NationalitiesSummary,
  NationalityRow,
  NpsView,
  PngCategory,
  PreferenceQuestion,
  PreferenceSource,
  PreferenceStatus,
  SurveyGuest,
} from './guests'

export type {
  BookingExtra,
  ExtrasListSummary,
  ExtrasVersionDetail,
} from './extras'

export type {
  ClientDocumentFilters,
  ClientDocumentRow,
  Delivery,
  DeliveryKind,
  DeliveryStatus,
  DocumentKind,
  DocumentPlanKind,
  DocumentPlanRow,
  DocumentStatus,
  IssuedDocument,
  ManifestIssued,
  ManifestKind,
  ManifestRow,
  ManifestVersion,
} from './documents'

export type {
  Alert,
  AlertCounts,
  AlertKind,
  AlertKindRow,
  AlertSeverity,
} from './alerts'

export type {
  CommercialMetrics,
  HotelKpis,
  MetricDefinition,
  MetricScope,
  MetricWindow,
} from './metrics'

export type {
  ReportCadence,
  ReportDefinition,
  ReportRun,
  ReportRunStatus,
  ReportSubscription,
  RunReportInput,
  UpdateSubscriptionInput,
} from './reports'

export type {
  CompleteLink,
  Offer,
  OfferChannel,
  OfferStatus,
  OfferType,
} from './offers'

export type {
  AttributionInput,
  AttributionTouch,
  CheckoutCreated,
  CheckoutExtended,
  CheckoutPath,
  CheckoutStatus,
  CheckoutSubmitted,
  CompleteBooking,
  CompleteDeclaration,
  CompleteGuest,
  CompleteReservation,
  EngineCabin,
  EngineCountry,
  EngineDeparture,
  EngineEventName,
  EngineEventParams,
  EngineEventsAccepted,
  EngineEventsInput,
  EngineFeed,
  EngineItinerary,
  EngineOffer,
  EngineOfferType,
  EngineQuote,
  EngineRates,
  EngineSettings,
  EngineWaitlist,
  PriceChangedError,
  PromoCheck,
  QuestionnaireAnswersInput,
  QuestionnaireView,
  SurveyInput,
  SurveyQuestion,
  SurveyView,
  MarketingLeadInput,
  UnsubscribeView,
} from './engine'

export type {
  ActivityEvent,
  ActivityKpis,
  Contact as CrmContact,
  ContactBooking,
  ContactDuplicate,
  ContactFilters,
  ContactMerge,
  ContactMergeResult,
  ContactProfile,
  ContactType,
  ContactUnmergeResult,
  EventCatalogueRow,
  Lifecycle,
  OwnershipRow,
  RetrySyncFailure,
  ScheduledJobCatalogueRow,
  ScheduledJobRun,
  ContactSegment,
  SyncFailure,
  SyncIdentityRow,
  SyncKpis,
  ActivityInput,
  AssignDealInput,
  AttributionModelRow,
  BindDealInput,
  Campaign,
  CampaignBooking,
  CampaignInput,
  CampaignMeasures,
  CampaignOffer,
  CampaignUpdate,
  CompleteTaskInput,
  ConsentPurpose,
  ConsentRegisterRow,
  ContactActivity,
  ContactConsentEntry,
  ContactConsentState,
  CrmTask,
  DataMapRow,
  DealDetail,
  DealInput,
  DealStage,
  DealType,
  DeliveryKpis,
  DeliveryRow,
  AutomationAudience,
  AutomationKind,
  AutomationRow,
  AutomationSwitchInput,
  Journey,
  JourneyEnrolment,
  JourneyEnrolmentStatus,
  JourneyStep,
  JourneyStepAction,
  JourneyUpdate,
  B2bPartnerRow,
  Conversation,
  ConversationLinkInput,
  ConversationMessage,
  ConversationReplyInput,
  ConversationStatus,
  MessageDirection,
  MessageTemplate,
  MessageTemplateVersion,
  PublishTemplateInput,
  Segment,
  SegmentCondition,
  SegmentDimension,
  SegmentInput,
  SegmentKind,
  SegmentUpdate,
  SegmentVocabulary,
  TemplateDraftInput,
  TemplatePreviewInput,
  MoveDealInput,
  PipelineColumn,
  PipelineDeal,
  PipelineKpis,
  RecordConsentInput,
  StageMapRow,
  TaskInput,
  TaskKind,
  TaskKpis,
  TaskUpdate,
  TimelineItem,
} from './crm'

export type {
  CloseSubjectRequestInput,
  EraseSubjectRequestInput,
  SubjectRequest,
  SubjectRequestChannel,
  SubjectRequestInput,
  SubjectRequestStatus,
  SubjectRequestType,
} from './privacy'

export type {
  AgenciesKpis,
  Agency,
  AgencyListItem,
  AgencyStatus,
  AgencyUser,
  AgencyUserInput,
  AgencyUserStatus,
  AgencyUserUpdate,
  CancellationBandLabel,
  CommissionPayout,
  CommissionPayoutInput,
  CommissionRow,
  CommissionStatus,
  Payment,
  PaymentKind,
  PaymentLink,
  PaymentListItem,
  PaymentMethod,
  PaymentOption,
  PaymentOptions,
  PaymentStatus,
  PaymentsKpis,
  PortalActivity,
  PortalPreview,
  ReconciliationReport,
  ReconciliationRow,
  RefundRequest,
  RefundsRules,
  RefundStatus,
  ResumePortalInput,
  SalesMaterial,
  SalesMaterialKind,
  StoreSalesMaterialInput,
  SuspendPortalInput,
} from './payments'

export type {
  AcceptPortalInviteInput,
  PortalAgency,
  PortalAvailabilityRow,
  PortalBooking,
  PortalCommission,
  PortalForgotInput,
  PortalLoginInput,
  PortalMaterial,
  PortalNetRates,
  PortalPaymentLinkInput,
  PortalRequest,
  PortalRequestCreated,
  PortalRequestInput,
  PortalResetInput,
  PortalSeason,
  PortalSession,
  PortalStayAvailability,
  PortalStayBooking,
  PortalStayCalendar,
  PortalStayCommission,
  PortalStayRates,
  PortalStayRequestInput,
  PortalStayRoomType,
} from './portal'

export type {
  Availability,
  AvailabilityCounts,
  BlockClaim,
  BlockReason,
  Cabin,
  CabinAvailability,
  CabinCategory,
  CabinState,
  CabinUnavailableError,
  CabinUnavailableItem,
  CalendarCell,
  CalendarDeparture,
  CalendarGrid,
  CalendarRow,
  ClaimHolder,
  ClaimKind,
  ClaimSummary,
  NightCalendar,
  NightCell,
  NightClaim,
  NightCounts,
  NightRoom,
  NightState,
  Departure,
  DepartureKpis,
  DepartureLayout,
  DepartureListItem,
  DepartureLocks,
  DepartureMutationResponse,
  DepartureStatus,
  EngineLabel,
  EngineLabelCode,
  EngineLabelTone,
  GenerateSeasonResult,
  ContentCompleteness,
  HoldType,
  InternalBlock,
  Itinerary,
  ItineraryCompleteness,
  ItineraryDefaults,
  ItineraryGradient,
  ItineraryListItem,
  ItineraryPair,
  ItineraryStatus,
  PropertyContent,
  RoomRow,
  RoomTypeContent,
  RoomTypePhoto,
  WaitlistNotice,
  Yacht,
} from './inventory'
